# Site name
title = "SðŸ¦€sha's blog"
default_language = "en"

# The URL the site will be built for
base_url = "https://scrabsha.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

generate_feed = true

highlight_code = true
highlight_theme = "nord"

# Theme
theme = "zola-pickles"

[extra]
# Put all your custom variables here
author = "Sasha Pourcelot"

copyright = "Written by Sasha Pourcelot, delivered under the [CC BY SA v4.0](https://creativecommons.org/licenses/by-sa/4.0/) license. Black Lives Matter."
subtitle = "Some thoughts about my computer science journey"
